export const projects = [
  {
    name: "my-Portfolio-Live-",
    slug: "my-portfolio-live",
    visibility: "Public",
    date: "Jan 2026",
    isPublic: true,
    description: "My personal portfolio website built with modern web technologies including TypeScript and Next.js.",
    image: "/portfoliov3.png",
    tags: ["TypeScript", "MIT License"],
    github: "https://github.com/SankethAbilas/my-Portfolio-Live-",
    webapp: "https://sanketh-abilas.netlify.app/",
  },
  {
    name: "Online-Video-Browsing-System-OOP-",
    slug: "online-video-browsing-system",
    visibility: "Public",
    date: "Dec 2025",
    isPublic: true,
    description: "An Object-Oriented Programming based Online Video Browsing System developed using Java.",
    image: "/placeholder.svg",
    tags: ["Java"],
    github: "https://github.com/SankethAbilas/Online-Video-Browsing-System-OOP-",
    webapp: "#",
  },
  {
    name: "Hotel-Management-System-BergHaus-Bangalore-",
    slug: "hotel-management-system-berghaus",
    visibility: "Public",
    date: "Dec 2025",
    isPublic: true,
    description: "A comprehensive Hotel Management System for BergHaus Bangalore, built with TypeScript.",
    image: "/placeholder.svg",
    tags: ["TypeScript", "MIT License"],
    github: "https://github.com/SankethAbilas/Hotel-Management-System-BergHaus-Bangalore-",
    webapp: "#",
  },
  {
    name: "Mern-Think-board",
    slug: "mern-think-board",
    visibility: "Public",
    date: "Jun 2025",
    isPublic: true,
    description: "A collaborative thinking board application built using the MERN stack (MongoDB, Express, React, Node.js).",
    image: "/placeholder.svg",
    tags: ["MERN Stack"],
    github: "https://github.com/SankethAbilas/Mern-Think-board",
    webapp: "#",
  },
  {
    name: "portfolio",
    slug: "portfolio-private",
    visibility: "Private",
    date: "Mar 2025",
    isPublic: false,
    description: "Private repository for portfolio development and experimentation.",
    image: "/placeholder.svg",
    tags: ["TypeScript", "MIT License"],
    github: "#",
    webapp: "#",
  },
  {
    name: "Simple-To-Do-List-using-React-js",
    slug: "simple-todo-list-react",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A clean and simple To-Do List application built with React.js and CSS.",
    image: "/placeholder.svg",
    tags: ["CSS", "React.js"],
    github: "https://github.com/SankethAbilas/Simple-To-Do-List-using-React-js",
    webapp: "#",
  },
  {
    name: "Online-App-Store",
    slug: "online-app-store",
    visibility: "Public",
    date: "Nov 2024",
    isPublic: true,
    description: "An online application store platform developed using PHP.",
    image: "/placeholder.svg",
    tags: ["PHP"],
    github: "https://github.com/SankethAbilas/Online-App-Store",
    webapp: "#",
  },
  {
    name: "Eshop-E-Commerce-Demo-",
    slug: "eshop-ecommerce-demo",
    visibility: "Public",
    date: "Sep 2024",
    isPublic: true,
    description: "A demonstration of an E-commerce platform built with PHP.",
    image: "/placeholder.svg",
    tags: ["PHP"],
    github: "https://github.com/SankethAbilas/Eshop-E-Commerce-Demo-",
    webapp: "#",
  },
  {
    name: "test",
    slug: "test-repo",
    visibility: "Private",
    date: "Sep 2024",
    isPublic: false,
    description: "Test repository for HTML experimentation.",
    image: "/placeholder.svg",
    tags: ["HTML"],
    github: "#",
    webapp: "#",
  },
  {
    name: "Pagination-DEMO-",
    slug: "pagination-demo",
    visibility: "Public",
    date: "Sep 2024",
    isPublic: true,
    description: "A demonstration project showcasing pagination implementation in PHP.",
    image: "/placeholder.svg",
    tags: ["PHP"],
    github: "https://github.com/SankethAbilas/Pagination-DEMO-",
    webapp: "#",
  },
  {
    name: "Shopping-cart",
    slug: "shopping-cart-demo",
    visibility: "Public",
    date: "Aug 2024",
    isPublic: true,
    description: "A simple shopping cart implementation using HTML.",
    image: "/placeholder.svg",
    tags: ["HTML"],
    github: "https://github.com/SankethAbilas/Shopping-cart",
    webapp: "#",
  },
  {
    name: "sankethabilas",
    slug: "sankethabilas-config",
    visibility: "Public",
    date: "Aug 2024",
    isPublic: true,
    description: "Config files for my GitHub profile.",
    image: "/placeholder.svg",
    tags: ["Config"],
    github: "https://github.com/SankethAbilas/sankethabilas",
    webapp: "#",
  },
  {
    name: "Web-Hosting-Demo-",
    slug: "web-hosting-demo",
    visibility: "Public",
    date: "Aug 2024",
    isPublic: true,
    description: "A demonstration project for web hosting concepts using JavaScript.",
    image: "/placeholder.svg",
    tags: ["JavaScript"],
    github: "https://github.com/SankethAbilas/Web-Hosting-Demo-",
    webapp: "#",
  },
  {
    name: "Creating-Payment-Gateway-DEMO-",
    slug: "payment-gateway-demo",
    visibility: "Public",
    date: "Jul 2024",
    isPublic: true,
    description: "A demonstration of creating a payment gateway integration using Hack language.",
    image: "/placeholder.svg",
    tags: ["Hack"],
    github: "https://github.com/SankethAbilas/Creating-Payment-Gateway-DEMO-",
    webapp: "#",
  },
  {
    name: "Email-Sending-Demo-",
    slug: "email-sending-demo",
    visibility: "Public",
    date: "Jul 2024",
    isPublic: true,
    description: "A demonstration of email sending functionality using PHP.",
    image: "/placeholder.svg",
    tags: ["PHP"],
    github: "https://github.com/SankethAbilas/Email-Sending-Demo-",
    webapp: "#",
  },
  {
    name: "Sanketh2121",
    slug: "sanketh2121",
    visibility: "Public",
    date: "Jul 2024",
    isPublic: true,
    description: "Repository for Sanketh2121.",
    image: "/placeholder.svg",
    tags: [],
    github: "https://github.com/SankethAbilas/Sanketh2121",
    webapp: "#",
  },
  {
    name: "Creating-Image-Uploader",
    slug: "creating-image-uploader",
    visibility: "Public",
    date: "Jul 2024",
    isPublic: true,
    description: "A project demonstrating how to create an image uploader using JavaScript.",
    image: "/placeholder.svg",
    tags: ["JavaScript"],
    github: "https://github.com/SankethAbilas/Creating-Image-Uploader",
    webapp: "#",
  },
  {
    name: "My-Chat-App",
    slug: "my-chat-app",
    visibility: "Public",
    date: "Jul 2024",
    isPublic: true,
    description: "A chat application built with PHP.",
    image: "/placeholder.svg",
    tags: ["PHP"],
    github: "https://github.com/SankethAbilas/My-Chat-App",
    webapp: "#",
  }
];
