export const projects = [
  {
    name: "Blood Donation System 2.0",
    slug: "blood-donation-system-2",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "An advanced Blood Donation System built with PHP and MySQL, featuring secure authentication, donor management, doctor dashboard, and comprehensive blood inventory tracking with ER diagram and session management.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/picc1.png?alt=media&token=0a84134c-e442-40cd-b9d5-2d06091e8bac",
    tags: ["PHP", "MySQL", "HTML", "CSS", "JavaScript"],
    github: "https://github.com/VehanRajintha/Blood_Donation_System_02",
    webapp: "https://github.com/VehanRajintha/Blood_Donation_System_02",
  },
  {
    name: "ChatX - Real-time Chat App",
    slug: "chatx-realtime-chat-app",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A fully responsive real-time chat web application built with React and Firebase, featuring user authentication, real-time messaging, and modern UI design. Deployed on Netlify for seamless user experience.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/pic1.jpg?alt=media&token=8419be03-f0e6-4a09-9e5b-06ca587ce371",
    tags: ["React", "Firebase", "JavaScript", "HTML", "CSS"],
    github: "https://github.com/VehanRajintha/ChatX",
    webapp: "https://chatlk.netlify.app/",
  },
  {
    name: "Google Keep Clone",
    slug: "google-keep-clone",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A feature-rich Google Keep clone application with note-taking capabilities, task management, and modern UI design. Built with modern web technologies for optimal user experience.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/pic.png?alt=media&token=7a1701b7-70e9-4ea9-9d4a-124b6d68fcb8",
    tags: ["React", "JavaScript", "HTML", "CSS"],
    github: "https://github.com/VehanRajintha/Google_Keep_clone",
    webapp: "https://github.com/VehanRajintha/Google_Keep_clone",
  },
  {
    name: "Snake Mouse Interactive Game",
    slug: "snake-mouse-interactive-game",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "An interactive Snake and Mouse game with engaging gameplay mechanics. Features smooth animations, responsive controls, and modern game design principles for an immersive gaming experience.",
    image: "https://raw.githubusercontent.com/VehanRajintha/Snake_mouse_interactive/main/snake.gif",
    tags: ["JavaScript", "HTML5", "CSS3", "Game Development"],
    github: "https://github.com/VehanRajintha/Snake_mouse_interactive",
    webapp: "https://github.com/VehanRajintha/Snake_mouse_interactive",
  },
  {
    name: "Google Cloud Backup Magisk Module",
    slug: "google-cloud-backup-magisk-module",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A Magisk module for unlimited Google Cloud backup functionality on Android devices. Provides enhanced backup capabilities and storage management for Android users with root access.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/ChatGPT%20Image%20Aug%2017%2C%202025%2C%2003_18_23%20PM.png?alt=media&token=89094dba-1dca-4e5f-961a-f3f84faf1987",
    tags: ["Android", "Magisk", "Shell Scripting", "System Development"],
    github: "https://github.com/VehanRajintha/Free-Unlimited-Google-Cloud-Backup-Magisk-Module",
    webapp: "https://github.com/VehanRajintha/Free-Unlimited-Google-Cloud-Backup-Module",
  },
  {
    name: "Dashboard Template for Enveto",
    slug: "dashboard-template-enveto",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A professional dashboard template designed for Enveto platform, featuring modern UI/UX design, responsive layout, and comprehensive dashboard components for business applications.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202025-08-17%20152032.png?alt=media&token=1d65b50f-17cc-4a59-9bb4-1231759d0428",
    tags: ["HTML", "CSS", "JavaScript", "Dashboard", "UI/UX"],
    github: "https://github.com/VehanRajintha/Dashboard_templatefor_Enveto",
    webapp: "https://vehanrajintha.github.io/Dashboard_templatefor_Enveto/",
  },
  {
    name: "MaternaSync - Pregnancy Management",
    slug: "maternasync-pregnancy-management",
    visibility: "Private",
    date: "Dec 2024",
    isPublic: false,
    description: "A comprehensive AI-powered pregnancy management system built with React, Node.js, and Firebase. Features include AI assistant, autonomous booking, real-time chat, appointment management, and multi-language support for Sri Lankan users.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202025-08-17%20152643.png?alt=media&token=d9a31d05-26cf-460c-bcda-769249444167",
    tags: ["React.js", "Node.js", "Firebase", "AI/ML", "Tailwind CSS"],
    github: "https://github.com/VehanRajintha/Pregnancy_Management_System",
    webapp: "https://github.com/VehanRajintha/Pregnancy_Management_System",
  },
  {
    name: "Oleseya Travels Website",
    slug: "oleseya-travels-website",
    visibility: "Private",
    date: "Dec 2024",
    isPublic: false,
    description: "A modern travel website for Oleseya Travels featuring destination showcases, booking systems, and responsive design. Built with modern web technologies for optimal user experience and travel planning.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202025-08-17%20152406.png?alt=media&token=ac97baf3-c6f6-4f71-8b4b-d892510fa7cf",
    tags: ["HTML", "CSS", "JavaScript", "Travel", "Responsive Design"],
    github: "https://github.com/VehanRajintha/Oleseya-travels",
    webapp: "https://olesyatravels.lk/",
  },
  {
    name: "Sunil Reisen Travel Platform",
    slug: "sunil-reisen-travel-platform",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A comprehensive travel platform for Sunil Reisen featuring tour packages, booking management, and customer portal. Built with modern web technologies and optimized for travel industry requirements.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202025-08-17%20152943.png?alt=media&token=7523bafd-5392-41e1-871f-ef6d080198fe",
    tags: ["React", "JavaScript", "CSS", "Travel Platform", "Booking System"],
    github: "https://github.com/VehanRajintha/sunilreisen",
    webapp: "https://reisenmitsunil.com/",
  },
  {
    name: "Model Management Lanka",
    slug: "model-management-lanka",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A professional model management platform for the Sri Lankan fashion industry. Features include portfolio management, booking systems, and modern UI design for model agencies and clients.",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202025-08-17%20153210.png?alt=media&token=67301a9d-5d9a-417d-892a-b7981b6458a9",
    tags: ["Next.js", "React", "JavaScript", "Model Management", "Portfolio"],
    github: "https://github.com/VehanRajintha/modelmanegement.lk",
    webapp: "https://posesstudios.com/",
  },
  {
    name: "Spy Mic",
    slug: "spy-mic",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "The website allows users to turn their Bluetooth earbuds or AirPods into spy microphones. By connecting their earbuds to their smartphone and visiting the website, users can remotely listen to the surrounding environment.",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic%20(1).jpg?alt=media&token=a0a0f03c-0bed-4bb2-9932-9ca889f454bf",
    tags: ["Html", "Css", "Js"],
    github: "https://github.com/VehanRajintha/BT-Reverse-hearing-website-spy-mic-",
    webapp: "https://spymic.netlify.app/",
  },
  {
    name: "Car Racing Game",
    slug: "car-racing-game",
    visibility: "Public",
    date: "Jun 2023",
    isPublic: true,
    description: "A 3D Car Racing game For PC and Android developed by using Unity game engine.",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic.png?alt=media&token=90609034-341d-41ed-84f0-bc0f93cd0c87",
    tags: ["C#"],
    github: "https://github.com/VehanRajintha/Unity-Full-Project-Car-Racing-Game-",
    webapp: "https://www.mediafire.com/file/axg48uoidiyzwrf/Project.zip/file",
  },
  {
    name: "VrMusic",
    slug: "vrmusic",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "VrMusic is a Online music streaming app (Sportify Alternative) made by using kotlin",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/WhatsApp%20Image%202024-06-12%20at%2013.03.02_c72ff11c.jpg?alt=media&token=e3ec0baa-103c-42b4-a0b6-1bd50d46d9be",
    tags: ["Kotlin"],
    github: "https://github.com/VehanRajintha/VrMusic",
    webapp: "https://github.com/VehanRajintha/VrMusic/releases/download/VrMusic/app-release.apk",
  },
  {
    name: "Stationary Website",
    slug: "stationary-website",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A company business Stationary website for Nanaslo PVT/LTD made with html,css & js",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/Screenshot%202024-06-29%20124118.png?alt=media&token=3884c843-1942-47d4-adeb-972d08368b85",
    tags: ["Html", "Css", "Javascript"],
    github: "https://github.com/VehanRajintha/Nanaslo_The-Stationary_Website",
    webapp: "https://vehanrajintha.github.io/Nanaslo_The-Stationary_Website/index.html",
  },
  {
    name: "X-UI English Panel",
    slug: "x-ui-english-panel",
    visibility: "Public",
    date: "Oct 2022",
    isPublic: true,
    description: "Another Translated-to-English Version of X-UI; with some of more advanced features implemented. Everything is in English (Serverside setup + Serverside UI + Web UI).",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/IMG_20231009_094949.jpg?alt=media&token=8a2e7d1c-99ad-4f0b-b776-c4cf72bf6eeb",
    tags: ["Shell", "Go", "Dockerfile"],
    github: "https://github.com/VehanRajintha/X-UI-English-",
    webapp: "https://github.com/VehanRajintha/X-UI-English-/releases/download/x-ui-linux-amd64.tar.gz/x-ui-linux-amd64.tar.gz",
  },
  {
    name: "webRTC Video Conference App",
    slug: "webrtc-video-conference-app",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "This is a webRTC Video Conference web app like zoom & google meet made by using react and ZEGOCLOUD",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/pic%20(1).jpg?alt=media&token=9c11bb6f-65be-4af8-9d41-5529fff4c9dd",
    tags: ["React"],
    github: "https://github.com/VehanRajintha/webRTC_VideoConverence_webApp",
    webapp: "https://vr-web-rtc-video-conferance-web-app.vercel.app/",
  },
  {
    name: "Animated Website",
    slug: "animated-website",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "This is a simple animated website project created by using html,css and js only",
    image: "https://firebasestorage.googleapis.com/v0/b/vehan-5008a.appspot.com/o/Screenshot%202024-07-13%20115501.png?alt=media&token=a57f538d-5e2e-45a4-a718-f2289a76abf0",
    tags: ["Html", "Css", "Javascript"],
    github: "https://github.com/VehanRajintha/web-developing",
    webapp: "https://vehanrajintha.github.io/web-developing/",
  },
  {
    name: "Travel Website",
    slug: "travel-website",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A responsive sri lankan Travel website made by using next.js",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/1.png?alt=media&token=0de0a991-5e72-4dd5-a5c2-cfe79137e628",
    tags: ["Next js"],
    github: "https://github.com/VehanRajintha/Travel_Website_Next-js",
    webapp: "https://travelserendipity.netlify.app/",
  },
  {
    name: "Pet Care System",
    slug: "pet-care-system",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A Full complete Pet Care System made by using PHP and Mysql.",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic1.png?alt=media&token=2122995f-d52d-4dd0-9e44-bad94700ebc4",
    tags: ["Php", "Mysql"],
    github: "https://github.com/VehanRajintha/Pet_Care_System",
    webapp: "https://github.com/VehanRajintha/Pet_Care_System",
  },
  {
    name: "Online Store Website",
    slug: "online-store-website",
    visibility: "Private",
    date: "Sep 2024",
    isPublic: false,
    description: "A company business Online Store website for Rambuke roots PVT/LTD made with html,css & js",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/Screenshot%202024-09-16%20153529.png?alt=media&token=55d53204-dba9-4224-927a-dbde34ef8fe4",
    tags: ["html", "css", "Javascript"],
    github: "Private repo",
    webapp: "https://rambukeroots.netlify.app/",
  },
  {
    name: "Hotel Reservation System",
    slug: "hotel-reservation-system",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A full system for Hotel Reservation made by using php & mysql",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic1%20(1).png?alt=media&token=6059ee95-4fd8-4cee-b162-47330dc9b83e",
    tags: ["Php", "Mysql"],
    github: "https://github.com/VehanRajintha/Hotel_Reservation_System",
    webapp: "https://github.com/VehanRajintha/Hotel_Reservation_System",
  },
  {
    name: "Blood Donation System",
    slug: "blood-donation-system",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A full complete Blood Donation System with admin dashboard made by using php & mysql",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic3%20(1).jpg?alt=media&token=1434af81-d4fa-4870-bb2b-2bada1210b93",
    tags: ["Php", "Mysql"],
    github: "https://github.com/VehanRajintha/Blood_Donation_System",
    webapp: "https://github.com/VehanRajintha/Blood_Donation_System",
  },
  {
    name: "Vehicle Auction System",
    slug: "vehicle-auction-system",
    visibility: "Public",
    date: "Jun 2024",
    isPublic: true,
    description: "A Full complete system for Vehicle Auction made by using php & mysql",
    image: "https://firebasestorage.googleapis.com/v0/b/my-portfallio-website.appspot.com/o/pic1%20(1).jpg?alt=media&token=54d2e5bc-cf3f-46a5-a555-fab7500fe87d",
    tags: ["Php", "Mysql"],
    github: "https://github.com/VehanRajintha/Vehicle_Auction_System",
    webapp: "https://github.com/VehanRajintha/Vehicle_Auction_System",
  },
  {
    name: "Android Apple BLE Spoof",
    slug: "android-apple-ble-spoof",
    visibility: "Public",
    date: "Oct 2023",
    isPublic: true,
    description: "A security research project that allows you to spoof Android devices as Apple BLE proximity pairing devices. This tool demonstrates Bluetooth Low Energy protocol interactions and security testing capabilities.",
    image: "https://raw.githubusercontent.com/VehanRajintha/Spoof-your-Android-as-Apple-BLE-Proximity-Pairing-device/main/20231008_224809.gif",
    tags: ["Java", "Android", "Bluetooth", "BLE", "Security Research"],
    github: "https://github.com/VehanRajintha/Spoof-your-Android-as-Apple-BLE-Proximity-Pairing-device",
    webapp: "https://github.com/VehanRajintha/Spoof-your-Android-as-Apple-BLE-Proximity-Pairing-device",
  },
  {
    name: "Sorillus Crack - Security Tool",
    slug: "sorillus-crack",
    visibility: "Public",
    date: "Nov 2023",
    isPublic: true,
    description: "A security research tool for educational purposes. This project demonstrates software analysis and security testing capabilities in a controlled environment for learning and research purposes.",
    image: "https://raw.githubusercontent.com/VehanRajintha/Sorillus-Crack/main/demo.png",
    tags: ["Security Research", "Tools", "Educational", "Analysis"],
    github: "https://github.com/VehanRajintha/Sorillus-Crack",
    webapp: "https://github.com/VehanRajintha/Sorillus-Crack",
  },
  {
    name: "MCP System - Car Maintenance Platform",
    slug: "mcp-system-car-maintenance",
    visibility: "Public",
    date: "Dec 2024",
    isPublic: true,
    description: "A modern AI-powered vehicle maintenance prediction and management platform built with Next.js. Effortlessly track, predict, and schedule maintenance for your fleet with beautiful dashboards and intuitive workflows.",
    image: "/MCP.png",
    tags: ["Next.js", "TypeScript", "AI/ML", "shadcn/ui", "Fleet Management"],
    github: "https://github.com/VehanRajintha/MCPSystem",
    webapp: "https://mcpsystem.netlify.app/",
  },
  {
    name: "Portfolio V2 - 3D Interactive Website",
    slug: "portfolio-v2-3d-website",
    visibility: "Private",
    date: "Jan 2023",
    isPublic: false,
    description: "A stunning 3D interactive portfolio website built with React and Three.js. Features immersive 3D graphics, smooth animations with Framer Motion, and a modern Material-UI design. Includes 3D scenes, interactive elements, and a fully responsive layout.",
    image: "/portfoliov2.png",
    tags: ["React", "Three.js", "Framer Motion", "Material-UI", "3D Graphics"],
    github: "https://github.com/VehanRajintha/My_Portfollio_2",
    webapp: "https://vehanrajintha.netlify.app/",
  },
  {
    name: "Portfolio V3",
    slug: "portfolio-v3",
    visibility: "Private",
    date: "Jan 2025",
    isPublic: false,
    description: "A modern, responsive portfolio website built with Next.js 15 and TypeScript. Features dark mode support, animated transitions, GitHub contributions integration, and a comprehensive showcase of projects, achievements, and blog posts. Built with shadcn/ui components and Tailwind CSS for optimal performance and user experience.",
    image: "/portfoliov3.png",
    tags: ["Next.js", "TypeScript", "shadcn/ui", "Tailwind CSS", "Dark Mode"],
    github: "Private repo",
    webapp: "https://vehan.netlify.app/",
  },
  {
    name: "MCQ Practice Platform",
    slug: "mcq-practice-platform",
    visibility: "Public",
    date: "Nov 2024",
    isPublic: true,
    description: "A modern web application for students to practice multiple choice questions before exams. Features 5 subject modules with lecture-based organization, interactive quiz system, real-time validation, and detailed explanations.",
    image: "/mcq.png",
    tags: ["Next.js", "TypeScript", "shadcn/ui", "Tailwind CSS", "Education"],
    github: "https://github.com/VehanRajintha/mcq_practise_v1",
    webapp: "https://mcq-practise-v1.vercel.app/",
  },
  {
    name: "Blood Donation Management System",
    slug: "blood-donation-system",
    visibility: "Public",
    date: "Mar 2023",
    isPublic: true,
    description: "A comprehensive Java desktop application for managing blood donation operations. Features secure authentication, user/admin dashboards, blood donation management, inventory tracking, donor registration, and appointment scheduling.",
    image: "https://raw.githubusercontent.com/VehanRajintha/-blood-donation-system/main/pic1.png",
    tags: ["Java", "Swing GUI", "MySQL", "Maven", "Desktop Application"],
    github: "https://github.com/VehanRajintha/-blood-donation-system",
    webapp: "https://github.com/VehanRajintha/-blood-donation-system",
  },
  {
    name: "PO-S Website",
    slug: "po-s-website",
    visibility: "Public",
    date: "Sep 2024",
    isPublic: true,
    description: "A Next.js website project built with TypeScript and Tailwind CSS. Features modern UI components, optimized performance, and responsive design. Includes animated elements and dynamic content.",
    image: "https://raw.githubusercontent.com/VehanRajintha/PO-S_Website/main/pic.jpg",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Responsive Design"],
    github: "https://github.com/VehanRajintha/PO-S_Website",
    webapp: "https://github.com/VehanRajintha/PO-S_Website",
  },
];

